authApp/urls.py
"""Urls for Financial app."""
from .views import (EstiDetailsView, UploadPdfView, SettingView, UpdateEstimationLineView, 
                UpdateEstimationTotalsView, AudatexDetailsView, UpdateDamagesTableView, UpdateEstimateTableView,
                MitchelDetailsView, UpdateMitchelEstimationTableView, DownloadCsvView)
from django.urls import path


urlpatterns = [
    path('details/<int:pk>/', EstiDetailsView.as_view(), name='estimation-detail'),
    path('audatex_details/<int:pk>/', AudatexDetailsView.as_view(), name='audatex-detail'),
    path('mitchel_details/<int:pk>/', MitchelDetailsView.as_view(), name='mitchel-detail'),
    path('upload_pdf/', UploadPdfView.as_view(), name='upload-pdf'),
    path('settings/', SettingView.as_view(), name='settings'),
    path('update_estimate_line/', UpdateEstimationLineView.as_view(), name='update-estimate-line'),
    path('update_estimate_total/', UpdateEstimationTotalsView.as_view(), name='update-estimate-total'),
    path('update_damagestable_line/', UpdateDamagesTableView.as_view(), name='update-damagestable-line'),
    path('update_estimate_table/', UpdateEstimateTableView.as_view(), name='update-estimate-table'),
    path('update_mitchell_estimation_table/', UpdateMitchelEstimationTableView.as_view(), name='update-mitchell-estimate-table'),
    path('download-csv/', DownloadCsvView, name='download-csv'),
]

estiscrub/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import HomeView, SignupView, LoginView, \
    LogoutView, ForgotView, DeleteEstimationView, \
    DeleteAudatexView, DeleteMitchelView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^signup/$', SignupView.as_view(), name='signup'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^forgot/$', ForgotView.as_view(), name='forgot'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'), name='password_reset_complete'),
    url(r'^esti/', include(('authApp.urls', 'details'), namespace='details')),
    url(r'^(?P<pk>[0-9]+)/delete-estimation/$', DeleteEstimationView.as_view(), name='delete_estimation'),
    url(r'^(?P<pk>[0-9]+)/delete-audatex/$', DeleteAudatexView.as_view(), name='delete_audatex'),
    url(r'^(?P<pk>[0-9]+)/delete-mitchel/$', DeleteMitchelView.as_view(), name='delete_mitchel'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/audatex_billing_details.html
<div class="notes_section">
	<label>Notes</label>
	<div class="notes_content"></div>
</div>
<div class="summary">
	<label>ESTIMATE Table</label>
	<table class="table billing_table">
	<thead>
		<tr>
			<th scope="col">Parts</th>
			<th scope="col">Rate Hour</th>
			<th scope="col">amount</th>
			<th scope="col">Action</th>
		</tr>
	</thead>
  <tbody>
  	{% for est in audatex.estimatetable.all %}
		<tr>
			<td>{{est.parts}}</td>
			<td>{{est.rate_hour}}</td>
			<td>{{est.amount}}</td>
			<td>
				<button type="button" class="btn btn-primary edit_estimate_table_btn" estimate_table_id="{{est.id}}"
					parts="{{est.parts}}" rate_hour="{{est.rate_hour}}" amount="{{est.amount}}">
					Edit
				</button>
			</td>
		</tr>
	{% endfor %}
  </tbody>
</table>
</div>

<script>
	$(".edit_estimate_table_btn").click(function(){
		$("#estimate_table_id").val($(this).attr("estimate_table_id"));
		$("#estimate_table_parts").val($(this).attr("parts"));
		$("#estimate_table_rate_hour").val($(this).attr("rate_hour"));
		$("#estimate_table_amount").val($(this).attr("amount"));
		$("#edit_estimate_table_modal").modal('show');
	});
</script>

templates/audatex_table_section_detail.html
<table class="table">
	<thead>
		<tr>
			<th scope="col">Line</th>
			<th scope="col">Op</th>
			<th scope="col">Guide</th>
			<th scope="col">MC</th>
			<th scope="col">Description</th>
			<th scope="col">MFR Part No</th>
			<th scope="col">Price</th>
			<th scope="col">Adj</th>
			<th scope="col">B</th>
			<th scope="col">Hours</th>
			<th scope="col">R</th>
			<th scope="col">Action</th>
		</tr>
	</thead>
  <tbody>
  	{% for line in audatex.damagestable.all %}
	<tr>
		<th scope="row">{{line.line}}</th>
		<td>{{line.op}}</td>
		<td>{{line.guide}}</td>
		<td>{{line.mc}}</td>
		<td>{{line.description}}</td>
		<td>{{line.mfr_partno}}</td>
		<td>{{line.price}}</td>
		<td>{{line.adj}}</td>
		<td>{{line.b}}</td>
		<td>{{line.hours}}</td>
		<td>{{line.r}}</td>
		<td>
			<button type="button" class="btn btn-primary edit_damagestable_line_btn" damagestable_line_id="{{line.id}}"
				line="{{line.line}}" op="{{line.op}}" guide="{{line.guide}}" mc="{{line.mc}}" description="{{line.description}}" mfr_partno="{{line.mfr_partno}}" 
				price="{{line.price}}" adj="{{line.adj}}" b="{{line.b}}" hours="{{line.hours}}" r="{{line.r}}">
				Edit
			</button>
		</td>
	</tr>
	{% endfor %}
	<tr class="subtotal_row">
		<th scope="row"></th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<!-- <td style="border-bottom:1px solid black;">SUBTOTALS</td> 
		<td style="border-bottom:1px solid black;"></td>
		<td style="border-bottom:1px solid black;">4,179.19</td>
		<td style="border-bottom:1px solid black;">23.0</td>
		<td style="border-bottom:1px solid black;">9.2</td>
		-->
	</tr>
  </tbody>
</table>

<script>
	$(".edit_damagestable_line_btn").click(function(){
		$("#damagestable_line_id").val($(this).attr("damagestable_line_id"));
		$("#damagestable_line").val($(this).attr("line"));
		$("#damagestable_op").val($(this).attr("op"));
		$("#damagestable_guide").val($(this).attr("guide"));
		$("#damagestable_mc").val($(this).attr("mc"));
		$("#damagestable_description").val($(this).attr("description"));
		$("#damagestable_mfr_partno").val($(this).attr("mfr_partno"));
		$("#damagestable_price").val($(this).attr("price"));
		$("#damagestable_adj").val($(this).attr("adj"));
		$("#damagestable_b").val($(this).attr("b"));
		$("#damagestable_hours").val($(this).attr("hours"));
		$("#damagestable_r").val($(this).attr("r"));
		$("#edit_damagestable_line_modal").modal('show');
	});
</script>

templates/forgot.html
{% extends "base.html" %}
{% load static widget_tweaks %}
{% block title %}Forgot password{% endblock %}

{% block content %}
<div class="container">
	<div class="settings_section">
		<h4>Forgot Password</h4>
		<div class="col-md-8">
			<form method="post" action=".">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<label>{{field.label}}</label>
						{{field|add_class:'form-control'}}
					</div>
				{% endfor %}
				<button type="submit" class="btn btn-primary">Send</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
	<div class="row home_section">
		<div class="col-md-4">
			<div class="filter_section">
				<!-- <div class="search-container">
					<input type="text" name="search" class="form-control" placeholder="Search">
					<button type="submit"><i class="fa fa-search"></i></button>
				</div> -->
				<div class="search_category">
					<label>Search by Category</label>
					<select id="inputState" class="form-control" onchange="location = this.value;">
				        <option value="/?type=ccc" {% if active_type == "ccc" %} selected {% endif %}>CCC</option>
				        <option value="/?type=audatex" {% if active_type == "audatex" %} selected {% endif %}>Audatex</option>
				        <option value="/?type=mitchell" {% if active_type == "mitchell" %} selected {% endif %}>Mitchell</option>
			      	</select>
				</div>
				<div class="history_section">
					<div class="history_header">
						<label>History</label>
					</div>
					<div class="row history_container">
						{% for a in 'test' %}
							<div class="history_list">
								<div class="col-md-4"><label>7/20/19</label></div>
								<div class="col-md-8">
									<span>Commerce Insurance Co.</span><span>2015 Volkswagen Jetta GTI</span>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-8">
			<div class="listing_section">
				{% if active_type == "ccc" %} 
					{% for estimation in my_estimations %}
						<a href="{% url 'details:estimation-detail' estimation.id %}" style="z-index: 999;">
							<div class="main_list">
								<div class="main_list_header">
									{% if estimation.is_new %}
										<img src="static/images/new_banner.png" width="5%"></img>
									{% endif %}
									<label>Job no: <span>{{estimation.jobnumber}}</span></label>
									<label>Est Type: <span>{{estimation.estimate_type}}</span></label>
									<label>Date: <span>9/06/2019</span></label>
									<span class="share_delete_section">
										<span><i class="fa fa-share-alt" aria-hidden="true"></i></span>
										<form method="post" action="{% url 'delete_estimation' pk=estimation.id %}" style="display: inline-block;">{% csrf_token %} 
											<button type="submit" style="border: none;background: none;">
												<i class="fa fa-trash" aria-hidden="true"></i>
											</button>
										</form> 
									</span>
								</div>
								<div class="row main_list_container">
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Insur:</label></div>
											<div class="col-md-10"><span>{{estimation.insurance_company}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Adj:</label></div>
											<div class="col-md-10"><span>{{estimation.adjuster}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>IAC:</label></div>
											<div class="col-md-10"><span>{{estimation.iac}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Appr:</label></div>
											<div class="col-md-10"><span>{{estimation.insurance_appraisal}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Veh:</label></div>
											<div class="col-md-10"><span>{{estimation.vehicle_detail}}</span></div>
										</div>
									</div>
								</div>
							</div>
						</a>
					{% endfor %}
				{% endif %}
				
				{% if active_type == "audatex" %}
					{% for audatex in audatex_objs %}
						<a href="{% url 'details:audatex-detail' audatex.id %}" style="z-index: 999;">
							<div class="main_list">
								<div class="main_list_header">
									{% if audatex.is_new %}
										<img src="static/images/new_banner.png" width="5%"></img>
									{% endif %}
									<label>Job no: <span>-</span></label>
									<label>Audatex Type: <span>{{audatex.audatex_type}}</span></label>
									<label>Date: <span>{{audatex.datetime}}</span></label>
									<span class="share_delete_section">
										<span><i class="fa fa-share-alt" aria-hidden="true"></i></span>
										<form method="post" action="{% url 'delete_audatex' pk=audatex.id %}" style="display: inline-block;">{% csrf_token %} 
											<button type="submit" style="border: none;background: none;">
												<i class="fa fa-trash" aria-hidden="true"></i>
											</button>
										</form> 
									</span>
								</div>
								<div class="row main_list_container">
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Insur:</label></div>
											<div class="col-md-10"><span>{{audatex.claim}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Add1:</label></div>
											<div class="col-md-10"><span>{{audatex.address1}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Agent:</label></div>
											<div class="col-md-10"><span>{{audatex.agent}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Add2:</label></div>
											<div class="col-md-10"><span>{{audatex.address2}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Claim No.:</label></div>
											<div class="col-md-10"><span>{{audatex.claim_number}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Appraiser Name:</label></div>
											<div class="col-md-10"><span>{{audatex.appraiser_name}}</span></div>
										</div>
									</div>
								</div>
							</div>
						</a>
					{% endfor %}
				{% endif %}
				{% if active_type == "mitchell" %} 
						{% for mitchel in mitchel_objs %}
						<a href="{% url 'details:mitchel-detail' mitchel.id %}" style="z-index: 999;">
							<div class="main_list">
								<div class="main_list_header">
									{% if mitchel.is_new %}
										<img src="static/images/new_banner.png" width="5%"></img>
									{% endif %}
									<label>Est ID: <span>{{mitchel.estimate_id}}</span></label>
									<label>Audatex Type: <span>{{mitchel.mitchel_type}}</span></label>
									<label>Date: <span>{{mitchel.estimate_date}}</span></label>
									<span class="share_delete_section">
										<span><i class="fa fa-share-alt" aria-hidden="true"></i></span>
										<form method="post" action="{% url 'delete_mitchel' pk=mitchel.id %}" style="display: inline-block;">{% csrf_token %} 
											<button type="submit" style="border: none;background: none;">
												<i class="fa fa-trash" aria-hidden="true"></i>
											</button>
										</form> 
									</span>
								</div>
								<div class="row main_list_container">
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Insur:</label></div>
											<div class="col-md-10"><span>{{mitchel.insco_info}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Adj:</label></div>
											<div class="col-md-10"><span>{{mitchel.adjuster_info}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Owner:</label></div>
											<div class="col-md-10"><span>{{mitchel.owner}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Appr:</label></div>
											<div class="col-md-10"><span>{{mitchel.appraiser_info}}</span></div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-2"><label>Veh.:</label></div>
											<div class="col-md-10"><span>{{mitchel.description}}</span></div>
										</div>
									</div>
								</div>
							</div>
						</a>
					{% endfor %}
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="signup-form">
    <form action="." method="post">
        {% csrf_token %}
		<h2>Login</h2>
		<p class="hint-text">Make yourself login</p>
        <div class="form-group">
        	{{login.email}}
        </div>
		<div class="form-group">
            {{login.password}}
        </div>
		<div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
        </div>
	   <div class="text-center">Don't have an account? <a href="{% url 'signup' %}">Sign up</a></div>
       <div class="text-center"><a href="{% url 'forgot' %}">Forgot Password?</a></div>
    </form>
</div>
{% endblock %}

templates/login_header.html
<nav class="navbar navbar-default navbar-expand-xl navbar-light main_header">
  <div class="navbar-header d-flex col">
    <a class="navbar-brand" href="#"><i class="fa fa-cube"></i>Esti<b>Scrub</b></a>     
    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle navbar-toggler ml-auto">
      <span class="navbar-toggler-icon"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <!-- Collection of nav links, forms, and other content for toggling -->
  <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
    {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav">
        <li class="nav-item active"><a href="{% url 'home' %}" class="nav-link"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right ml-auto">
        <li class="nav-item dropdown user_profile">
          <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle user-action"><i class="fa fa-user-circle"></i> {{request.user.first_name}} {{request.user.last_name}}<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'details:settings' %}" class="dropdown-item"><i class="fa fa-cog fa-fw" aria-hidden="true"></i>Settings</a></li>
            <li><a href="{% url 'logout' %}" class="dropdown-item"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></li>
          </ul>
        </li>
        <li class="nav-item"><a href="#" class="nav-link notifications" data-toggle="modal" data-target="#create_esti"><i class="fa fa-edit"></i></a></li>
        <li class="nav-item"><a href="#" class="nav-link messages"><i class="fa fa-envelope-o"></i><span class="badge">10</span></a></li>
      </ul>
    {% else %}
      <ul class="nav navbar-nav navbar-right ml-auto">
        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link notifications">Login</a></li>
        <li class="nav-item"><a href="{% url 'signup' %}" class="nav-link messages">Signup</a></li>
      </ul>
    {% endif %}
  </div>
</nav>

templates/password_reset_confirm.html
{% extends "base.html" %}
{% load static widget_tweaks %}
{% block title %}Forgot password{% endblock %}

{% block content %}
<div class="container">
	<div class="settings_section">
	  {% if validlink %}
	    <h4>Forgot Password</h4>
	    <div class="col-md-8">
			<form method="post">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<label>{{field.label}}</label>
						{{field|add_class:'form-control'}}
					</div>
				{% endfor %}
				{{form.errors.new_password2}}
				<button type="submit" class="btn btn-primary">Change password</button>
			</form>
		</div>
	  {% else %}
	    <p>
	      The password reset link was invalid, possibly because it has already been used.
	      Please request a new password reset <a href="{% url 'forgot' %}">Forgot Password</a>
	    </p>
	  {% endif %}
	</div>
</div>
{% endblock %}

templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

templates/settings.html
{% extends "base.html" %}
{% load static widget_tweaks %}
{% block title %}Settings{% endblock %}

{% block content %}
<div class="container">
	<div class="settings_section">
		<h4>Settings</h4>
		<div class="col-md-8">
			<form method="post" action=".">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<label>{{field.label}}</label>
						{{field|add_class:'form-control'}}
					</div>
				{% endfor %}
				<button type="submit" class="btn btn-primary">Change Password</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% block title %}Sign up{% endblock %}

{% block content %}
<div class="signup-form">
    <form action="." method="post">
        {% csrf_token %}
		<h2>Register</h2>
		<p class="hint-text">Create your account. It's free and only takes a minute.</p>
        <div class="form-group">
			<div class="row">
				<div class="col-md-6">{{signup.first_name}}</div>
				<div class="col-md-6">{{signup.last_name}}</div>
			</div>        	
        </div>
        <div class="form-group">
        	{{signup.email}}
        </div>
		<div class="form-group">
            {{signup.password1}}
        </div>
		<div class="form-group">
            {{signup.password2}}
        </div>        
        <div class="form-group">
			<label class="checkbox-inline">{{signup.agree_terms}} I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a></label>
		</div>
		<div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg btn-block">Register Now</button>
        </div>
	   <div class="text-center">Already have an account? <a href="{% url 'login' %}">Sign in</a></div>
       <div class="text-center"><a href="{% url 'forgot' %}">Forgot Password?</a></div>
    </form>
</div>
{% endblock %}